/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#07006c",
        "on-surface-variant": "#464554",
        "surface-container-lowest": "#ffffff",
        "on-background": "#1b1b23",
        "on-secondary-container": "#006172",
        "surface-container-high": "#e9e6f3",
        "surface": "#fcf8ff",
        "tertiary-container": "#b55d00",
        "error": "#ba1a1a",
        "outline": "#767586",
        "surface-container": "#efecf8",
        "on-tertiary-fixed": "#301400",
        "secondary-fixed": "#acedff",
        "secondary-container": "#57dffe",
        "secondary": "#00687a",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-surface": "#1b1b23",
        "primary-container": "#6063ee",
        "surface-dim": "#dbd8e4",
        "on-secondary-fixed": "#001f26",
        "outline-variant": "#c7c4d7",
        "surface-variant": "#e4e1ed",
        "inverse-surface": "#303038",
        "surface-container-low": "#f5f2fe",
        "on-tertiary-container": "#fffbff",
        "tertiary-fixed-dim": "#ffb783",
        "on-error": "#ffffff",
        "surface-container-highest": "#e4e1ed",
        "tertiary": "#904900",
        "primary-fixed": "#e1e0ff",
        "on-secondary": "#ffffff",
        "inverse-primary": "#c0c1ff",
        "on-primary-container": "#fffbff",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "surface-tint": "#494bd6",
        "surface-bright": "#fcf8ff",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#703700",
        "primary-fixed-dim": "#c0c1ff",
        "secondary-fixed-dim": "#4cd7f6",
        "on-secondary-fixed-variant": "#004e5c",
        "inverse-on-surface": "#f2effb",
        "background": "#fcf8ff",
        "tertiary-fixed": "#ffdcc5",
        "primary": "#4648d4"
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px"
      },
      spacing: {
        xl: "64px",
        xs: "8px",
        base: "4px",
        sm: "16px",
        lg: "40px",
        "margin-mobile": "16px",
        gutter: "24px",
        "margin-desktop": "48px",
        md: "24px"
      },
      fontFamily: {
        "title-md": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "display-lg": ["Inter"],
        "body-lg": ["Inter"],
        "label-caps": ["Inter"],
        "body-sm": ["Inter"]
      },
      fontSize: {
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
